### ISSUE TITLE
latest releases block paypal

### ISSUE THREAD

**Issue by conraid** [odebroqueville/contextSearch#159] opened 2023-11-26 11:00 UTC
For a while now, I have had to disable the extension in order to pay with paypal. Every time a site redirects to paypal payment the redirect, with popup opening, loops and nothing happens. By deactivating this extension everything is ok. It does the same on Linux and on Mac. With the latest version of FF and the extension.

**Comment by odebroqueville** [comment] 2023-11-26 16:50
How is Paypal being launched or redirected? Would you please press CTRL-ALT + I and visit the Console tab to see. if any errors appear. Can you share the url of the Paypal popup with me? Maybe the site breaks when the content script is injected. I'm not sure.

**Comment by conraid** [comment] 2023-11-29 16:04
For example in https://shop.universalmusic.it, when I go to pay it goes on a loop. If I disable the extension instead, it works.

I don't see any particular errors for paypal, only "state provided to "https://www.paypalobjects.com/webcaptcha/grcenterprise_v3_static.html" a partitioned cookie or access to storage resources as it is loaded in a third party context and dynamic state partitioning is active."

![immagine](https://github.com/odebroqueville/contextSearch/assets/1453776/eef9f721-e886-460c-b86d-02124bad1b25)

**Comment by odebroqueville** [comment] 2023-11-29 23:03
Unfortunately, I'm not able to place any orders from Switzerland any I don't want to purchase anything so I don't see how I can test this!

I'm having no trouble reaching the point where the Paypal popup appears for me to login.

<img width="1069" alt="Screenshot 2023-11-29 at 23 48 48" src="https://github.com/odebroqueville/contextSearch/assets/4818315/22c4ec09-4cf7-4932-86bc-e2e8594a12be">

There could be a conflict between Context Search and another extension. To rule this out, I would suggest that you allow Context Search to work in Incognito (or Private) mode. Then, open https://shop.universalmusic.it/ in Incognito mode and simulate a purchase up to the point where the Paypal popup appears. Then see if you're able to login without completing the purchase.

If things work that far, then it's likely that there's a conflict with another extension.

Another way to check if there's a conflict would be to temporarily disable all extensions except Context Search and see if you still encounter the issue. If not, then turn on each extension one-by-one to see which extension is conflicting with CS.

Do you have other links for which Paypal isn't working?

**Comment by conraid** [comment] 2023-12-06 12:38
No. I've tried twice, but I can't find it. There is something strange about it. By the way I deactivate one by one and it's okay. I leave all active and it works fine even with contextSearch active. I restart, and it doesn't go.
At this point I suspect something in my installation, although as mentioned it gave the same error on Linux and on Mac, with different extensions.

**Comment by odebroqueville** [comment] 2023-12-06 12:50
This is why I thought that it could be a security setting. Are you using a same VPN or firewall on all 3 operating systems? Also, I'd check your browser Privacy & Security settings:

<img width="1595" alt="Screenshot 2023-12-06 at 13 48 21" src="https://github.com/odebroqueville/contextSearch/assets/4818315/17556ee1-be19-494e-91b0-b39fde8c8e7c">

<img width="1595" alt="Screenshot 2023-12-06 at 13 49 14" src="https://github.com/odebroqueville/contextSearch/assets/4818315/3bfa1166-e135-46fb-9a0f-8e700feac86e">

**Comment by conraid** [comment] 2023-12-06 13:06
I don't use VPN and have basic settings.
Before the last update, I had no problems.

![immagine](https://github.com/odebroqueville/contextSearch/assets/1453776/5d35c9d8-18b9-4245-a172-a818fd5a3d41)

![immagine](https://github.com/odebroqueville/contextSearch/assets/1453776/43d439b7-fb6d-4372-bd8c-5e371e078f2f)

**Comment by odebroqueville** [comment] 2023-12-10 16:14
Are you using Firefox on 3 different devices or are you using VMs? Without knowing which extensions you use, I'm afraid I can't help you more as I'm not able to reproduce the issue on my end. I would disable all extensions except Context Search, and then check if logging into Paypal works. I would then progressively turn on each extension and check if you're able to log into Paypal.

**Comment by conraid** [comment] 2023-12-10 16:23
With 3 different devices.
As said doing that test works regularly, but then on ff restart no. I should do a test and reboot each time. It takes too much time :/
If I find out anything anyway I will let you know.
Thank you for your assistance.

**Comment by odebroqueville** [comment] 2024-01-11 19:50
Have you been able to make any progress?

**Comment by conraid** [comment] 2024-01-12 19:27
Oh yes, pardon. It creates problems together with the ALLOW RIGHT-CLICK (https://addons.mozilla.org/it/firefox/addon/re-enable-right-click/) extension.
If you want to try the problem also occurs on ebay and bandcamp.

**Comment by odebroqueville** [comment] 2024-01-12 20:04
@conraid Thanks for the feedback, Corrado. It would have been good of the developer to include a block list in the settings, so that you could add websites for which you don't want the extension to run. I know of another paid extension for mac that does something similar and more. It's called [StopTheMadness](https://underpassapp.com/StopTheMadness/install/firefox.html). It's first and foremost for Safari, but apparently it also works for Firefox. I haven't tested to see if it conflicts with Context Search, but I thought you might want to give it a try. Keep me posted!

**Comment by conraid** [comment] 2024-01-13 09:30
The situation is more complex, I try to explain. Today on bandcamp it recurred, and by removing any random extension instead it works. So I did some testing, and it works whatever extension I turn off. Basically whatever extension I take off, it works. On reboot, however, it crashes again, even without that extension I just removed. At this point I don't know what to think anymore.
If I uninstall "context search" instead, it always works.
But if the problem is only mine I would say let it go.

**Comment by odebroqueville** [comment] 2024-01-13 17:24
@conraid Quite frankly, Corrado, I don't know what to make of this. What puzzles me is that I can't reproduce this issue on my mac and, so far, you're the only person who's experienced this bug! What beats me is that you say you're encountering this issue on 3 different devices! At this stage, the only thing that I can suggest is for you to try an alternative to Context Search such as ContextSearch web-ext and see if the same issue arises.

**Comment by conraid** [comment] 2024-01-14 11:09
It is probably some conflict with something I use, which I cannot find, however. This one you suggested works fine. Just as yours worked fine until a few months ago. Too bad, because I find it simpler.

**Comment by odebroqueville** [comment] 2024-01-14 18:11
If the issue occurred a few months ago, what would be helpful, if you find the time, is to try to spot the first version of CS that causes the issue, maybe starting from v4.6.3 which was released mid September last year. The history of versions can be found here: https://addons.mozilla.org/en-US/firefox/addon/contextual-search/versions/.

**Comment by odebroqueville** [comment] 2024-08-04 13:43
I'm closing this issue as I don't see how to make it progress. Hope things have sorted themselves out with time!

**Closed by odebroqueville** 2024-08-04 13:43 UTC
Labels: bug
