### ISSUE TITLE
Suggestion: use FF search engines instead of your own list

### ISSUE THREAD

**Issue by ed65love** [odebroqueville/contextSearch#62] opened 2017-11-26 08:17 UTC
There was another extension that did this, and it's a big win, because it means users only need to deal with one set of search engines.

Also, you could throw away your UI code, and focus on the important stuff :)

What do you think?

**Comment by Smile4ever** [comment] 2017-11-26 08:19
It's a duplicate of https://github.com/odebroqueville/contextSearch/issues/60. Please read the reasoning there.

**Closed** 2017-11-26 17:53 UTC
