### ISSUE TITLE
Settings not kept after updates

### ISSUE THREAD

**Issue by sispli** [odebroqueville/contextSearch#173] opened 2024-01-25 11:18 UTC
Every time the add-on has been automatically updated, all settings go back to default and I have to adjust them again to my personal preferences. This is not a recent issue but already exists for a long time.

**Comment by odebroqueville** [comment] 2024-01-27 06:50
3 questions:
- which version of CS are you using?
- what is your OS?
- have you cleared the checkbox to "Reset preferences to default settings"?

**Comment by odebroqueville** [comment] 2024-02-03 06:49
@sispli I'm closing this issue as you have not responded.

**Comment by sispli** [comment] 2024-02-03 11:24
I do have responded on January 27th via e-mail (see attached screenshot
![Reply-Jan27](https://github.com/odebroqueville/contextSearch/assets/57145629/2c182d8b-54b0-4d03-b11e-8a837be7827f)
).

**Comment by odebroqueville** [comment] 2024-02-03 17:44
@sispli I'm sorry you're encountering this issue, which I'm having some difficulty to reproduce. Unfortunately, I can't test on Windows, so it may be related to the OS. But, like you say, I'm surprised nobody else has mentioned this annoying bug. Regarding your email, it looks like there was a glitch because I didn't receive it and there's no history of the message in this issue. But don't worry, I'll continue to try and solve this issue with you. Preferably use GitHub to respond if you can.

**Comment by sispli** [comment] 2024-02-03 18:29
Okay Olivier, I appreciate that you have re-opened the issue and will try to solve it. But how can you develop an add-on for Firefox on Windows platforms without being able to test it with that OS?

**Comment by odebroqueville** [comment] 2024-02-03 19:17
Usually, if a Firefox extension works without glitches on macOS it should also be the case for Windows and Linux. However, in the history of this extension, there has been one issue for users on Windows where pressing the Alt key would open Firefox's File menu (or something like that!) and I had prevented that default behaviour so that Alt-clicking would only open the Icons Grid. Users reported the issue on GitHub and there was a quick fix for that, but it's not something that I could pick up on macOS. Mind you no developer will ever be able to plan for all use cases and there's always going to be that odd use case nobody thought of that's going to happen some day. It can also even be due to a Firefox update (though it's less likely).

Anyway, just to let you know that I'm working on this issue, here's my request to Mozilla for support:
https://discourse.mozilla.org/t/is-storage-sync-preserved-after-extensions-are-updated/126878/12

**Comment by odebroqueville** [comment] 2024-03-10 19:06
Hello @sispli , I tested the following:
1) I installed version 4.7.7 from AMO
2) I changed 3 settings to be different from the default settings
3) I checked for extension updates which automatically installed v4.7.8
4) I visited the extension's options page and the changes I had made to the settings were preserved.

Please try the same method and let me know how it goes.

**Comment by sispli** [comment] 2024-03-10 19:30
Hello Oliver,
Everything works fine now: since version 4.7.8 the personalized settings are no longer reverted to default ones during updates of the add-on.
Thanks a lot for your time and efforts!

**Closed** 2024-03-25 20:33 UTC
Labels: bug

**Comment by sispli** [comment] 2024-03-25 20:39
Hello Oliver, Maybe it's concidence, but before you closed this bug report, I found out yesterday that all settings were back to default again, although the add-on was still on release 4.7.8, so no update had taken place since our previous communication 2 weeks ago. It looks like Firefox updates are able to reset add-on settings: I can not think of any other explanation. But please, don't put too much effort again to solve the problem again: it's not a big deal for me to adjust the setting to my likings,

**Comment by mr-brunes** [comment] 2024-08-13 08:53
I've also experienced this on Windows and it's occurred again just today. I note CS was updated yesterday but I'm not sure how to determine when FF has been updated. Is there a log somewhere? Meanwhile I'll try to find out and keep my own log of when this is happening. Tx to all for the info posted already.
