### ISSUE TITLE
The up/down move function are somewhat broken

### ISSUE THREAD

**Issue by AnonymFegis** [odebroqueville/contextSearch#11] opened 2019-03-24 07:51 UTC
Trying to move a search engine line in the preferences may move it one line, but more often just move the button sideways so that you have to "hunt" the button along the line. Moving the SE requires a random amount of clicks.

(FF 66.0.1)

**Comment by odebroqueville** [comment] 2019-03-25 16:02
Thanks for reporting this. It's due to the latest Firefox updates. A fix is ready and will soon be released.

**Comment by GuardianMajor** [comment] 2019-03-29 18:24
@odebroqueville Thank you, glad it is in the works because I just came to report it and saw that it's been said already. 

Before I open another issue in case they are related, does that also affect the fact that it doesn't save any settings and you can't delete anything? Or add a new search engine?

**Comment by odebroqueville** [comment] 2019-04-10 11:49
Can I close this issue? I believe it's been fixed with 3.72.

**Comment by grossherr** [comment] 2019-04-23 09:35
I don't think so. 

Using 3.72 and FF 66.0.2, it still behaves strangely. I'm running Ubuntu 18.04, in case it matters. 

What is happening: Random amount of clicks necessary, inability to move entry more than two lines, entries arbitrarily hanging at some point without being able to move them.

**Comment by odebroqueville** [comment] 2019-06-16 16:18
I'm not able to test this as I'm on macOS. I also can't reproduce the erratic behaviour on macOS.

**Closed** 2019-10-27 17:47 UTC
Labels: bug
