### ISSUE TITLE
Auto Save doesn't work

### ISSUE THREAD

**Issue by BluMoose2019** [odebroqueville/contextSearch#15] opened 2019-04-01 06:58 UTC
Unselecting Search Engines from the list isn't saved. Auto Save isn't working properly. Why eliminate the Save Preferences button? 

Also, exiting Firefox and reloading doesn't save changes.

**Comment by FerryP1** [comment] 2019-04-02 03:31
I am having the same issue. 
Also, the list of search engines resets to default every time I restart FF.

If this add-on doesn't start behaving, it'll be like Butters Stotch.... grounded for two weeks. 

But seriously, Olivier, please, PLEASE, fix these pesky issues. Your add-on is the one I use the most, by far, and I really miss it but in its current state it's pretty useless to me. <sad smiley face>

**Comment by odebroqueville** [comment] 2019-04-02 10:57
So sorry for the trouble! With thousands of code lines, things are getting harder to maintain or update! I've just released version 3.71 in a rush. It's still a bit buggy, especially the reset options (so please refrain from using the reset button in the mean time), but it should be usable.

**Comment by odebroqueville** [comment] 2019-04-02 16:30
I'm closing this issue as it is a duplicate of issue #10.

**Closed by odebroqueville** 2019-04-02 16:30 UTC
