### ISSUE TITLE
memory leak & high cpu usage in version 3.66

### ISSUE THREAD

**Issue by Speciesx** [odebroqueville/contextSearch#114] opened 2018-05-26 21:34 UTC
Last update causing a memory leak and high cpu usage.

![11](https://user-images.githubusercontent.com/1196375/40580366-0e6e1bbc-613d-11e8-812b-c6f64e7f81ae.PNG)
It took less than a min to reach this memory consumption and cpu usage is permanent between 40-60% on a 4 core cpu.

Firefox nightly

**Comment by tsoernes** [comment] 2018-05-26 23:08
+1

**Comment by frinnst** [comment] 2018-05-27 01:17
+1

took a while to figure out what caused my issues. indeed it's contextsearch :(

**Comment by peternm22** [comment] 2018-05-27 02:09
Running Firefox 60.0.1 and just ran into this with 3.66. Firefox was being a bit sluggish so I looked at the memory usage, and it was out of control.

I restarted Firefox with addons disabled and narrowed the cause down to Contextsearch.

**Comment by reisp01** [comment] 2018-05-27 02:37
I ended up here because of the exact same process of elimination. FF Beta 61.0b8 on macOS...

**Comment by pippinsoft** [comment] 2018-05-27 04:17
60.0.1 on linux here. Disk throughput is also very high. An SQLite journal file is being repeatedly created and removed in the profile folder: `storage-sync.sqlite-journal`

**Comment by peternm22** [comment] 2018-05-27 04:39
I took a quick look at the source code and the only recent changes seem to be to the favicon fetching. I'm guessing there is an infinite loop in there somewhere.

**Comment by pippinsoft** [comment] 2018-05-27 04:57
If I had to guess, I'd say it's the calls to `updateSearchEnginesIfNeeded()` with no argument.

**Comment by Simon-Tesla** [comment] 2018-05-27 07:10
Seeing the same issue here. No idea what happened, but reverting to an older version fixed it. FF 60.0.1 on Windows 10, was seeing 10GB memory usage and 60+% CPU.

**Comment by djinncoyote** [comment] 2018-05-27 07:26
I'm having the same issue.  Firefox 59.0.3, 64-bit, Windows 10.
![ff2](https://user-images.githubusercontent.com/29165665/40583478-81bcd8d6-615d-11e8-8d9d-f9d8ce426043.gif)

**Comment by Smile4ever** [comment] 2018-05-27 09:15
I have disabled version 3.66 until further investigation is carried out. Please let me know whether you are reverted back to version 3.65 automatically (or upon checking updates for the addon). Thank you.

**Comment by brnl** [comment] 2018-05-27 12:39
Confirmed! Installed 3.65 and it is stable again.

**Comment by GLLM** [comment] 2018-05-27 13:55
This lovely extension is the cause of my Firefox 60.0.1 crashing every 20 mins on Windows 64 Family 1803 ...
I was getting crazy, uninstalled some microsoft fix and nvidia drivers which I updated since I got the crash but it seems this addon is the root cause of the crash, using  up to 16GB of RAM at some point !!!!

**Comment by brnl** [comment] 2018-05-27 14:02
@GLLM Currently, you have to manually downgrade to 3.65 to fix this. See the "all versions" page on addons.mozilla.org: https://addons.mozilla.org/en-US/firefox/addon/contextual-search/versions/

**Comment by GLLM** [comment] 2018-05-27 15:01
Hey @brnl !
Hey, that's what I did and my PC is back to normal !
Thanks

**Comment by Smile4ever** [comment] 2018-05-27 15:09
@brnl I removed (instead of disabled) version 3.66 in the hopes that users are automatically downgraded. Thank you for letting me know.

**Comment by Caspy7** [comment] 2018-05-27 18:33
@Smile4ever 
I spoke with 2 individuals on Mozilla's IRC, one of which was a Moz dev and both seemed to confirm the behavior that users with 3.66 will *not* downgrade to 3.65 automatically.  It seems like a fixed version with a higher number will need to be pushed in order for affected users to get the fix.

**Comment by Smile4ever** [comment] 2018-05-27 18:41
@Caspy7 We're working on having a permanent fix in place as soon as possible.

**Comment by Smile4ever** [comment] 2018-05-27 19:04
Version 3.67 was released as a re-release of 3.65 to give existing users of 3.66 a good version as soon as possible.

**Comment by brnl** [comment] 2018-05-27 19:06
@Smile4ever I think that is a good workaround.

**Closed** 2018-06-07 16:51 UTC
Labels: bug
