### ISSUE TITLE
Unable to use custom keywords

### ISSUE THREAD

**Issue by Ainson** [odebroqueville/contextSearch#90] opened 2020-09-18 12:54 UTC
Seems only the keywords for the default search engines work.

It's been like this since the beginning, through several updates. I have tried to remove and add searches again and using different keywords, but no results.

The default searches work fine though, but it's impossible to change their keywords. It will simply default to the main search engine, as with all the other non-functioning keyword searches.

I have tried to uninstall and reinstall Context Search, but it makes no difference.

(Win 7, 64)

**Comment by odebroqueville** [comment] 2020-09-19 12:17
@Ainson Gee! That sounds like a major bug. Thanks for reporting it. I'll come back to you as soon as a fix is available.

**Comment by odebroqueville** [comment] 2020-09-19 12:54
@Ainson Actually, I'm not able to reproduce this bug. Please try the following and tell me how it goes:
1. From the extension's preferences page, copy the search query url for Baidu
2. Delete the Baidu search engine by clicking on the bin
3. Add a new search engine and call it Baidu, use the keyword 'x' and paste in the previously copied search query url
Try performing a search from the url adress bar by typing cs x whatever.
When I do the above, I get the expected search results from Baidu. What do you get?

**Comment by Ainson** [comment] 2020-09-19 15:42
Apart from the Baidu page not loading for some reason, the cs x whatever works (I can see it trying to load www.baidu.com/s?wd=whatever). (baidu.com without any extension is not loading either)

The x whatever will not work.

Maybe some Context search core files are corrupted? Is there a way to make sure all are wiped?

What about permissions or conflicts? I have no other similar extensions running, and bookmarks have no keywords either. I have also tried with symbols to check in case of conflict, but does not help.

**Comment by odebroqueville** [comment] 2020-09-19 16:36
@Ainson Whenever you perform a search in the url address bar (i.e. omnibox) you first have to precede the keyword with the letters 'cs' so that the extension knows that it is being called.
x whatever on its own will never work if it isn't preceded by cs.
The reason Baidu isn't working maybe means that you have a blocker of some sorts, could be at the DNS or firewall level.

**Comment by Ainson** [comment] 2020-09-19 16:44
Goodness, is that what you have to do every time to get the keywords working? I didn't realize.

I see now it's actually written in the text at Firefox, but I never saw it described anywhere else.

So not a bug. Just me assuming all necessary info would be in the preferences page, and not on the extension page as well.

But why do the default search engine work without the cs in front?

**Comment by odebroqueville** [comment] 2020-09-19 16:50
No worries, @Ainson. On my end searching without the cs just does a search with google.com because it is set as my default search engine. This is the correct and expected behaviour. I'm not sure why it works on your end, maybe if you clear your search history it'll stop working. I'll close the issue now, OK?

**Comment by Ainson** [comment] 2020-09-19 18:26
Ok. Thanks for the fast response.

**Closed** 2020-09-19 18:41 UTC
