### ISSUE TITLE
When closing a tab using a keyboard shortcut, a new one is automatically opened

### ISSUE THREAD

**Issue by jamespatriot** [odebroqueville/contextSearch#149] opened 2023-08-02 09:32 UTC
It seems to be extremely buggy in latest update. Whenever I close any browser tab, a new one is automatically opened with a baidu search from one of my Context Search sites. At first I thought it was malware, but then I realized it had to be this Firefox add-on. After disabling it, no more phantom context searches.

**Comment by odebroqueville** [comment] 2023-08-02 13:32
Thank you for reporting this bug. I will look into it asap.

**Comment by J-11** [comment] 2023-08-03 11:24
Hello, I have the same problem
os: win11 23H2
Firefox: 115.0.3
Context Search: 4.6.0
strokesplus: 0.5.7.4 [www.strokesplus.net](url)
It's hard to trigger this problem using keyboard ctrl+w. I found the problem while using strokesplus, and it's easy to reproduce with strokesplus gesture action sending hotkey ctrl+w. I don't know whose problem it is, but strokesplus works fine with other software. (strokesplus is a mouse gesture software, and of course I've tried to send ctrl+w with my mouse side button, but it doesn't trigger the bug)
![GIF 23-8-3 19-14-12](https://github.com/odebroqueville/contextSearch/assets/37813580/b07d6a17-6c84-44de-912f-2af159a51593)
![111](https://github.com/odebroqueville/contextSearch/assets/37813580/95ff889e-c0bc-46f6-b1b4-935452e6bd27)

**Comment by odebroqueville** [comment] 2023-08-03 11:52
Thank you for these helpful details. Do you have a keyboard shortcut defined for the search engine Ask? What is the left arrow icon you’re clicking on? When you click on the ‘x’ to close a tab, does it reproduce the bug or only when you’re using a keyboard shortcut?

I have to ask you these questions because I’m on Mac and sadly I don’t have the option to debug on Windows.

I feel there could be a conflict between strokesplus and CS when it comes to handling keyboard shortcuts.

If you allow and open CS in private mode (where other extensions are disabled) can you reproduce this bug?

On 3 Aug 2023, at 13:24, J-11 ***@***.***> wrote:


Hello, I have the same problem
os: win11 23H2
Firefox: 115.0.3
Context Search: 4.6.0
strokesplus: 0.5.7.4 www.strokesplus.net <x-msg://2/url>
It's hard to trigger this problem using keyboard ctrl+w. I found the problem while using strokesplus, and it's easy to reproduce with strokesplus gesture action sending hotkey ctrl+w. I don't know whose problem it is, but strokesplus works fine with other software. (strokesplus is a mouse gesture software, and of course I've tried to send ctrl+w with my mouse side button, but it doesn't trigger the bug)
 <https://user-images.githubusercontent.com/37813580/258095065-b07d6a17-6c84-44de-912f-2af159a51593.gif>
 <https://user-images.githubusercontent.com/37813580/258095105-95ff889e-c0bc-46f6-b1b4-935452e6bd27.png>

**Comment by odebroqueville** [comment] 2023-08-03 12:58
@jamespatriot @J-11  I think I found the problem. Would one of you mind testing the latest update (4.6.1) before I release it on AMO?

Please head over to the 'Code' page, download and unzip the Zip file:
![Screenshot 2023-08-03 at 14 50 01](https://github.com/odebroqueville/contextSearch/assets/4818315/318ee310-da9e-4775-9cbb-aa277e237b33)

Then, in the Firefox url address bar, type 'about:debugging' and click on 'Load temporary Add-on...'. Then select the manifest.json file from the folder where you unzipped the code:
![Screenshot 2023-08-03 at 14 51 07](https://github.com/odebroqueville/contextSearch/assets/4818315/c88c40d0-4bf6-49cd-9a5b-6b6d703351d7)

Please report if this fixes the bug or not. Thank you in advance for your help.

**Comment by J-11** [comment] 2023-08-03 14:17
Thank you for working so quickly, but the problem remains.
After using 4.6.1 I tried many possibilities, briefly:

1. Using keyboard shortcuts is almost no problem

2. When the page has no selected text, using strokesplus is no problem.
When the page has selected text, using strokesplus triggers the bug.

3. Reinstall CS (4.6.1 or 4.6.0) no problem.
Add a new search engine without shortcuts, bug occurs.
After setting shortcuts for the new search engine, no problem.

4. Now there is another problem, I can't delete keyboard shortcuts for search engines and the shortcuts always work even if the search engine is not activated. (In 4.6.1, it needs to have selected text in the page to trigger it)


I don't understand the difference between the hotkeys sent by strokesplus and the keyboard shortcuts, but that's probably the problem. Good luck with it.

--------

Here's the answer to a previous questions, but it's probably not much help.

-Do you have a keyboard shortcut defined for the search engine Ask?
No.

-What is the left arrow icon you’re clicking on? 
A button to reopen the page you just closed.

-When you click on the ‘x’ to close...
No problem using the "x". Almost no problem using keyboard shortcuts (only happened a couple times in 4.6.0).

-If you allow and open CS in private mode....
Private mode and closing other extensions, same problem.

**Comment by odebroqueville** [comment] 2023-08-03 18:02
Hi @J-11 , thank you for helping out. Concerning point 4, please note that kb shortcuts will always work whether they are checked to be displayed in the context menu or not.

I've identified some errors in the code and made some changes, but I can't test it on Windows. Would you be so kind as to go through your points 2 to 4 and let me know what still requires some fixing?

**Comment by J-11** [comment] 2023-08-03 19:11
Thank you @odebroqueville, everything is perfect now.
Although, I still can't remove the keyboard shortcuts for the search engine, but that doesn't matter to me.
Thanks again and have a good night/morning/afternoon!✧*｡٩(ˊωˋ*)و✧*｡

**Comment by odebroqueville** [comment] 2023-08-03 19:51
@J-11 "I still can't remove the keyboard shortcuts"... that is strange! I really thought I had fixed that! Have you tried clicking at the end of the keyboard shortcut to place the cursor there and then pressing the backspace key. Alternatively, you should be able to click at the beginning of the keyboard shortcut and press the delete key. If that still doesn't work, you should be able to select the entire keyboard shortcut and type another shortcut or press the delete key. Please let me know tomorrow if any of these methods work or not. Thank YOU and good night. (I'm based in Switzerland!)

**Comment by shyun3** [comment] 2023-08-04 05:54
Getting this issue also

**Comment by J-11** [comment] 2023-08-04 08:11
Hi, good morning @odebroqueville, compared to 4.6.0, in 4.6.1 I was indeed able to remove keyboard shortcuts using the backspace key, but after refreshing the shortcuts came back. Maybe there's a save button I'm not noticing, or something is preventing it from auto-saving.

**Comment by odebroqueville** [comment] 2023-08-04 09:26
Good morning @J-11 . It's strange, I can't reproduce what you're experiencing on my Mac. Could you make a screen recording like the one below so that I can see what's happening:

https://imgur.com/a/6bNa44t

**Comment by odebroqueville** [comment] 2023-08-04 10:13
@J-11 I think it's fixed now. Would you mind testing one last time please?

**Comment by mocnisima** [comment] 2023-08-04 10:52
Same problem, I have logitech g602 mouse and ctrl-w programed on one taster, with keyboard everything works ok.

**Comment by J-11** [comment] 2023-08-04 12:08
@odebroqueville Yeah! I can't find any more problems. Thank you very much!

**Comment by odebroqueville** [comment] 2023-08-04 13:15
@J-11 Hi, your English is excellent! Much better than my Chinese! Thank you so much for your help. Take care.

@mocnisima Will be releasing 4.6.1 shortly on AMO. Please leet me know if it fixes your issue or not. Thank you in advance.

**Comment by odebroqueville** [comment] 2023-08-05 09:51
@jamespatriot @shyun3 @mocnisima May I close this issue or is anyone still experiencing this bug?

**Comment by mocnisima** [comment] 2023-08-05 09:52
For me everything works now.

**Closed** 2023-08-11 16:31 UTC
Labels: bug
