### ISSUE TITLE
Search list altered, new items added, but not by me!

### ISSUE THREAD

**Issue by Ainson** [odebroqueville/contextSearch#80] opened 2020-08-10 09:44 UTC
A bizarre situation where a lot of searches has been added to my list, but not by me! What's going on?

I can't even remove them. If I do, they reappear at next browser start.

Can sites access and edit my extensions now? Seems like a serious security breach.

**Comment by odebroqueville** [comment] 2020-08-10 21:26
1. Are the search engines that appear different from the default search engines (as they are listed here: https://github.com/odebroqueville/contextSearch/blob/master/defaultSearchEngines.json) ?
2. Which check boxes are checked amongst the Reset options on the extension's Preferences page?

**Comment by Ainson** [comment] 2020-08-11 05:41
Yes it looks indeed that they are the default searches, but the 'Force reload of default search engines list' -option is off and has always been off (unchecked). Like I say, they all of a sudden appeared. I will check and uncheck that option to see if that helps. All the other boxes are also unchecked in the Reset options.

**Comment by odebroqueville** [comment] 2020-08-15 16:18
I'm using Firefox Developer Edition 80.0b8 (64-bit) on macOS Catalina 10.15.6 and I'm unable to reproduce your issue. Which OS are you using? Which browser? Which versions? Are you  sure that you are using the latest version of Context Search made available, i.e. 3.9.5?

**Comment by Ainson** [comment] 2020-08-15 17:08
Yes it is the latest version, but the issue has gone away after checking and unchecking all the option boxes.

I suspect this all started after an update. Maybe the update changes my settings, but it didn't show in the GUI?

**Comment by odebroqueville** [comment] 2020-08-17 13:55
OK, well I'll close the issue for now as I'm not able to reproduce the bug.

**Closed by odebroqueville** 2020-08-17 13:55 UTC
Labels: bug
