### ISSUE TITLE
Feature request: use Firefox's own search engine list

### ISSUE THREAD

**Issue by Pseudavid** [odebroqueville/contextSearch#60] opened 2017-11-25 13:33 UTC
Why have two lists of available search engines, one in Firefox preferences, the other in the extension preferences? Isn't is possible that the extension uses the same engines as the browser? Or, at least, importing the search list from the browser. Thanks!

**Comment by Smile4ever** [comment] 2017-11-25 13:44
Thank you for your suggestion. This is a much requested feature that we can't currently implement:

* Mozilla does not currently provide a WebExtensions api to list the search engines that are installed. This will probably come in the future, see https://bugzilla.mozilla.org/show_bug.cgi?id=1268401 and https://bugzilla.mozilla.org/show_bug.cgi?id=1352598
* Importing the existing search engines was deemed too difficult. A pull request that does this (a code submission) is always welcome.

For now, you will have two lists.

We plan to make it easier to add search engines to Context Search by offering this:
https://github.com/odebroqueville/contextSearch/issues/30

**Comment by Pseudavid** [comment] 2017-11-25 13:50
Thanks and sorry if duplicate, I searched in the issue list but didn't find anything about this. My problem is more about the not too easy way of adding the new search engines than having two lists.

Can we somehow use [Mycroft](http://mycroftproject.com) to add engines to the extension?

**Comment by Smile4ever** [comment] 2017-11-25 14:55
> Thanks and sorry if duplicate, I searched in the issue list but didn't find anything about this. My problem is more about the not too easy way of adding the new search engines than having two lists.

We got many requests by mail and by reviews. It's no trouble for us that you opened this issue.

> Can we somehow use Mycroft to add engines to the extension?

That's what I would consider under #30.

**Comment by odebroqueville** [comment] 2017-11-25 15:02
I'm closing this issue as we currently see this as a duplicate of issue #30. When the above mentioned bugs have been resolved by Bugzilla, we'll consider creating a new item to import search engines from firefox's search bar into Context Search.

**Closed by odebroqueville** 2017-11-25 15:02 UTC

**Comment by Thaodan** [comment] 2017-12-29 01:25
Could you make the existing bug more describing or tag it that its better to find when looking this?
